"AI-Safety":
- changed-files:
  - any-glob-to-any-file: "tests/ai_safety/**"

"ModelRegistry":
- changed-files:
  - any-glob-to-any-file: "tests/ai_hub/**"

"ModelServing":
- changed-files:
  - any-glob-to-any-file: "tests/model_serving/**"

"Workbenches":
- changed-files:
  - any-glob-to-any-file: "tests/workbenches/**"

"GitHub":
- changed-files:
  - any-glob-to-any-file: ".github/**"

"Documentation":
- changed-files:
  - any-glob-to-any-file: "docs/**"

"Utilities":
- changed-files:
  - any-glob-to-any-file: "utilities/**"
